YoubetDao/youbet-task

src/pages/dashboard/index.tsx
src/pages/mytask/empty-task.tsx
src/pages/mytask/index.tsx
src/pages/mytask/task-item.tsx
src/pages/project/index.tsx
src/pages/task/empty-task.tsx
src/pages/task/index.tsx
src/pages/task/task-item.tsx
src/router/pages.tsx
src/service/index.ts
src/types/index.ts

feat: task card improvement

---

src/pages/dashboard/index.tsx
src/pages/mytask/index.tsx
src/pages/mytask/task-item.tsx
src/pages/task/task-item.tsx
src/pages/tutorials/index.tsx

1. mytask link is missing
2. Dashboard project display redirects to the project task page
3. Align tutorial line breaks

feat: fix ui

---

package.json
pnpm-lock.yaml
src/pages/profile/index.tsx

- Add a claim button and it's loadiing status
- Optimized some UI effects 
- Fixed some UI issues in small screen sizes

feat: claiming ui

---

src/components/leaderboard-row.tsx
src/pages/mytask/task-item.tsx
src/pages/task/task-item.tsx
src/pages/tutorials/index.tsx

1. leaderboard description
2. task-item

feat: fix ui 0827

---

src/pages/project/index.tsx
src/service/instance.ts

fix: change qs array format to comma

---

src/pages/task-detail/index.tsx
src/service/index.ts
src/service/instance.ts
src/types/index.ts

To allow admin assign issues to any user, we need to change the way to claim user.
User need to comment the issue first, so that admin can assign it to them.
Also we change the terms to "Apply\Applied\Assigned"

feat: use comment to apply issue

---

src/components/icons.tsx
src/components/layout/MobileSidebar.tsx
src/components/layout/Sidebar.tsx
src/constants/data.ts
src/pages/pull-request/index.ts
src/pages/task-apply/index.ts
src/router/index.tsx
src/router/pages.tsx
src/types/index.ts

previously, we don't support render children menu. This commit implement it in a simple manner. We need to rewrite it in the future.

feat: support children menu

---

src/pages/tutorials/index.tsx

correct text-ellipsis behavior on tutorial card

fix(tutorial): correct text-ellipsis behavior on tutorial card

---

src/pages/dashboard/index.tsx
src/pages/mytask/index.tsx
src/pages/task/index.tsx
src/service/index.ts
src/types/index.ts

feat: support task filter

---

src/components/forms/user-auth-form.tsx
src/components/layout/shared/Header.tsx
src/components/layout/shared/Sidebar.tsx
src/constants/data.ts
src/pages/callback/index.tsx
src/service/index.ts
src/service/instance.ts
src/store/index.ts
src/types/index.ts

feat: authentication

---

src/components/layout/shared/Sidebar.tsx
src/constants/data.ts

resolve issue with using Jotai atoms outside React component

fix(jotai): resolve issue with using Jotai atoms outside React component

---

src/components/loading-cards.tsx
src/components/task/index.tsx
src/pages/profile/index.tsx
src/pages/project/index.tsx
src/pages/pull-request/index.tsx
src/pages/task-apply/index.tsx
src/pages/task-detail/index.tsx
src/pages/tutorial/index.tsx
src/pages/tutorials/index.tsx

feat: unify loading cards

---

src/pages/tutorial/index.tsx

fix: click not responsive

---

package.json
pnpm-lock.yaml
src/components/ui/drawer.tsx
src/pages/period/index.tsx
src/service/index.ts
src/types/index.ts

feat: period transfer detail

---

package.json
pnpm-lock.yaml
src/components/md-renderer.tsx
src/lib/md-processor.ts

feat: add katex

---

src/components/ui/popover.tsx

fix: import repo scroll

---

src/components/layout/shared/ConnectButton.tsx
src/components/layout/shared/Header.tsx
src/components/layout/shared/Sidebar.tsx
src/components/layout/tutorial/tutorial-toc.tsx
src/constants/data.ts
src/pages/callback/index.tsx
src/pages/dashboard/index.tsx
src/pages/login/index.tsx
src/pages/myrewards/index.tsx
src/pages/profile/index.tsx
src/pages/tutorial/index.tsx
src/pages/tutorials/index.tsx
src/service/instance.ts
src/store/index.ts
src/store/userInfo/index.ts
src/store/userInfo/store.ts
src/store/userInfo/type.ts

Unified handling of the central data source in Jotai by encapsulating it within the store. Centralize the get and set methods to prevent data source confusion in the future. This approach will also facilitate the addition of global data sources in a similar manner if needed.

refactor: store

---

src/pages/admin/completedTask.tsx
src/pages/period/index.tsx

修复了admin下面的分页问题，原因是在分页参数的传递过程中没有传递page和pageSize，导致分页请求并没有发出。怀疑上面MyTasks和MyRewards依然存在这种问题，但是我的号没有数据，所以没办法进行测试，于是没有盲目修改代码。

fix: fix pagination bug

---

src/constants/data.ts
src/pages/profile/index.tsx

feat: get explorer url from config file

---

src/components/task/index.tsx

Reverts YoubetDao/youbet-task#218

Revert "fix mytasks filter"

---

src/components/loading-cards.tsx

feat: vertical skeleton

---

src/pages/mytask/index.tsx

feat: remove padding

---

src/pages/project/index.tsx

feat: sticky projects info

---

src/components/task/task-card.tsx
src/pages/project/index.tsx

feat: add github icon

---

src/pages/task-detail/index.tsx

feat: go back to last page

---

src/pages/profile/_components/profile-banner.tsx

feat: update style

---

src/pages/task-detail/_components/QuestLog.tsx

feat: update task detail

---

src/pages/task-management/_components/TaskMgtTable.tsx
src/pages/task-management/index.tsx

feat: edit task management

---

src/pages/admin/BatchGrantDialog.tsx

fix: decimals

---

src/components/task/index.tsx
src/pages/projectdetail/TaskList.tsx

feat: search task
